version: '3.1'

networks:
  tech-talk:
    driver: bridge

services:
  mongo:
    image: mongo:4
    restart: always
    container_name: 'techTalk'
    networks:
      - tech-talk
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: techtalk
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/docker-entrypoint-initdb.d:ro